version: "3.8"
services:

    # PHP service
    app:
        build: docker/php/
        working_dir: /var/www/
        volumes:
            - './:/var/www'
            - './docker/php/php.ini:/usr/local/etc/php/conf.d/php.ini'
        networks:
            - app-network

    # MySQL database service
    mysql:
        image: mysql/mysql-server:8.0
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_ROOT_PASSWORD}'
            MYSQL_ROOT_HOST: "%"
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        env_file:
            - ./.env
        volumes:
            - './docker/data/mysql:/var/lib/mysql'
        networks:
            - app-network

    # Nginx service
    nginx:
        image: nginx:alpine
        ports:
            - '80:80'
        volumes:
            - ./:/var/www
            - ./docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - app-network

networks:
    app-network:
        driver: bridge
